name: MySecureMap
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.0.2
  http: ^0.13.6
  fl_chart: ^0.45.1
  google_maps_flutter: ^2.9.0
  intl: ^0.20.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  location: ^8.0.0
  google_maps_routes: ^1.1.2
  google_maps_webservice: ^0.0.19
  flutter_animate: ^4.1.1 
  shared_preferences: ^2.0.15
  dio: ^4.0.0
  permission_handler: ^10.4.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_polyline_points: ^1.0.0
  provider: ^6.0.5
  cached_network_image: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loading.gif
    - assets/logo.jpg

